# Open links from terminal output via fzf
set -g @plugin 'alberti42/tmux-fzf-links'

# Fuzzy search scrollback buffer
set -g @plugin 'roosta/tmux-fuzzback'
set -g @fuzzback-popup 1
set -g @fuzzback-popup-size '80%'
