tap 'rjyo/moshi'
tap 'steipete/tap'

cask 'claude'
cask 'claude-code@latest'
cask 'claude-devtools'
cask 'commander'
brew 'agent-browser'
brew 'rjyo/moshi/moshi-hook', restart_service: :changed
if OS.mac?
  brew 'steipete/tap/peekaboo'
end
