#!/usr/bin/env zsh

# Claude CLI completion for Zsh
# Generated by Claude
#
# To regenerate this file:
# 1. Run `claude-audit-completions` and reconcile this file against its report.
#    It surfaces hidden commands (absent from `claude --help` by design, e.g.
#    `attach`), missing flags, and choice-value drift against the installed binary.
# 2. As a manual cross-check for brand-new commands the scrape can miss, diff the
#    docs at https://code.claude.com/docs/en/cli-reference (docs run ahead of the
#    installed binary, so treat the binary as the source of truth for values).

_claude() {
  local line state

  local -a main_options=(
    '--add-dir[Additional directories to allow tool access to]:directories:_directories'
    '--agent[Agent for the current session]:agent:'
    '--agents[JSON object defining custom agents]:json:'
    '--allow-dangerously-skip-permissions[Enable bypassing permission checks as an option]'
    '--allowedTools[Comma or space-separated list of tool names to allow]:tools:'
    '--allowed-tools[Comma or space-separated list of tool names to allow]:tools:'
    '--append-system-prompt[Append a system prompt to the default system prompt]:prompt:'
    '--ax-screen-reader[Render screen-reader friendly output]'
    '--bare[Minimal mode: skip hooks, LSP, plugin sync, auto-memory, etc.]'
    '--betas[Beta headers to include in API requests]:betas:'
    '--bg[Start the session as a background agent and return immediately]'
    '--background[Start the session as a background agent and return immediately]'
    '--brief[Enable SendUserMessage tool for agent-to-user communication]'
    '--chrome[Enable Claude in Chrome integration]'
    '-c[Continue the most recent conversation]'
    '--continue[Continue the most recent conversation]'
    '--dangerously-skip-permissions[Bypass all permission checks]'
    '-d[Enable debug mode with optional category filtering]'
    '--debug[Enable debug mode with optional category filtering]:filter:'
    '--debug-file[Write debug logs to a specific file path]:path:_files'
    '--disable-slash-commands[Disable all skills]'
    '--disallowedTools[Comma or space-separated list of tool names to deny]:tools:'
    '--disallowed-tools[Comma or space-separated list of tool names to deny]:tools:'
    '--effort[Effort level for the current session]:level:(low medium high xhigh max)'
    '--exclude-dynamic-system-prompt-sections[Move per-machine sections into the first user message for prompt-cache reuse]'
    '--fallback-model[Automatic fallback model(s) when the default is overloaded]:model:'
    '--file[File resources to download at startup]:specs:'
    '--fork-session[When resuming, create a new session ID instead of reusing the original]'
    '--from-pr[Resume a session linked to a PR]:pr number or URL:'
    '-h[Display help for command]'
    '--help[Display help for command]'
    '--ide[Automatically connect to IDE on startup]'
    '--include-hook-events[Include all hook lifecycle events in the output stream]'
    '--include-partial-messages[Include partial message chunks as they arrive]'
    '--input-format[Input format (only works with --print)]:format:(text stream-json)'
    '--json-schema[JSON Schema for structured output validation]:schema:'
    '--max-budget-usd[Maximum dollar amount to spend on API calls]:amount:'
    '--mcp-config[Load MCP servers from JSON files or strings]:file or string:_files'
    '--model[Model for the current session]:model:(fable opus sonnet haiku)'
    '-n[Set a display name for this session]:name:'
    '--name[Set a display name for this session]:name:'
    '--no-chrome[Disable Claude in Chrome integration]'
    '--no-session-persistence[Disable session persistence]'
    '--output-format[Output format (only works with --print)]:format:(text json stream-json)'
    '--permission-mode[Permission mode to use for the session]:mode:(acceptEdits auto bypassPermissions manual dontAsk plan)'
    '--plugin-dir[Load a plugin from a directory or .zip for this session only]:path:_files'
    '--plugin-url[Fetch a plugin .zip from a URL for this session only]:url:'
    '-p[Print response and exit (useful for pipes)]'
    '--print[Print response and exit (useful for pipes)]'
    '--prompt-suggestions[Enable prompt suggestions]::value:(true false)'
    '--remote-control[Start an interactive session with Remote Control enabled]::name:'
    '--remote-control-session-name-prefix[Prefix for auto-generated Remote Control session names]:prefix:'
    '--replay-user-messages[Re-emit user messages from stdin back on stdout]'
    '-r[Resume a conversation]:session ID or search term:'
    '--resume[Resume a conversation]:session ID or search term:'
    '--safe-mode[Start with all customizations disabled for troubleshooting]'
    '--session-id[Use a specific session ID for the conversation]:uuid:'
    '--setting-sources[Comma-separated list of setting sources to load]:sources:'
    '--settings[Path to a settings JSON file or a JSON string]:file or json:_files'
    '--strict-mcp-config[Only use MCP servers from --mcp-config]'
    '--system-prompt[System prompt to use for the session]:prompt:'
    '--tmux[Create a tmux session for the worktree]'
    '--tools[Specify the list of available tools]:tools:'
    '--verbose[Override verbose mode setting from config]'
    '-v[Output the version number]'
    '--version[Output the version number]'
    '-w[Create a new git worktree for this session]:name:'
    '--worktree[Create a new git worktree for this session]:name:'
  )

  # shellcheck disable=SC2034
  local -a subcommands=(
    'agents:Manage background agents'
    'attach:Open a background session in this terminal'
    'auth:Manage authentication'
    'auto-mode:Inspect auto mode classifier configuration'
    'daemon:Manage the background-session supervisor'
    'doctor:Check the health of your Claude Code auto-updater'
    'gateway:Run the enterprise auth/telemetry gateway'
    'install:Install Claude Code native build'
    'kill:Stop a background session (alias for stop)'
    'logs:Print a background session'\''s recent output'
    'mcp:Configure and manage MCP servers'
    'plugin:Manage Claude Code plugins'
    'project:Manage Claude Code project state'
    'remote-control:Start the Remote Control server'
    'respawn:Restart a background session on the current binary'
    'rm:Delete a background session and its worktree'
    'setup-token:Set up a long-lived authentication token'
    'stop:Stop a background session (keeps its conversation)'
    'ultrareview:Run a cloud-hosted multi-agent code review'
    'update:Check for updates and install if available'
  )

  _arguments -C \
    "${main_options[@]}" \
    '1: :->command' \
    '*::arg:->args'

  case $state in
    command)
      _describe -t commands 'claude command' subcommands
      ;;
    args)
      case ${line[1]} in
        agents)
          _claude_agents
          ;;
        attach|logs|rm|stop|kill)
          _arguments \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:session id:'
          ;;
        respawn)
          _arguments \
            '--all[Restart all background sessions]' \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:session id:'
          ;;
        daemon)
          _claude_daemon
          ;;
        remote-control)
          _arguments \
            '-h[Display help]' \
            '--help[Display help]'
          ;;
        auth)
          _claude_auth
          ;;
        auto-mode)
          _claude_auto_mode
          ;;
        gateway)
          _arguments \
            '--config[Path to gateway YAML config]:path:_files' \
            '-h[Display help]' \
            '--help[Display help]'
          ;;
        mcp)
          _claude_mcp
          ;;
        plugin)
          _claude_plugin
          ;;
        project)
          _claude_project
          ;;
        ultrareview)
          _arguments \
            '--json[Print the raw bugs.json payload instead of formatted findings]' \
            '--timeout[Maximum minutes to wait for the review to finish]:minutes:' \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:target (PR number or base branch):'
          ;;
        install)
          _claude_install
          ;;
        *)
          _message 'no more arguments'
          ;;
      esac
      ;;
  esac
}

_claude_agents() {
  _arguments \
    '--add-dir[Additional directory to allow tool access to in dispatched sessions]:directory:_directories' \
    '--agent[Default agent for sessions dispatched from agent view]:agent:' \
    '--all[With --json: include completed sessions]' \
    '--allow-dangerously-skip-permissions[Make bypass-permissions mode available to dispatched sessions]' \
    '--cwd[Show only background sessions started under path]:path:_directories' \
    '--dangerously-skip-permissions[Alias for --permission-mode bypassPermissions]' \
    '--effort[Default effort level for sessions dispatched from agent view]:level:(low medium high xhigh max)' \
    '--json[Print active sessions as a JSON array and exit]' \
    '--mcp-config[MCP server configuration to apply to dispatched sessions]:config:_files' \
    '--model[Default model for sessions dispatched from agent view]:model:(fable opus sonnet haiku)' \
    '--permission-mode[Default permission mode for sessions dispatched from agent view]:mode:(acceptEdits auto bypassPermissions manual dontAsk plan)' \
    '--plugin-dir[Load plugins from specified directory for dispatched sessions]:path:_files' \
    '--setting-sources[Comma-separated list of setting sources to load]:sources:' \
    '--settings[Settings file or JSON string to apply to dispatched sessions]:file or json:_files' \
    '--strict-mcp-config[Only use MCP servers from --mcp-config in dispatched sessions]' \
    '-h[Display help]' \
    '--help[Display help]'
}

_claude_daemon() {
  local line state

  # shellcheck disable=SC2034
  local -a daemon_subcommands=(
    'run:Run the supervisor in the foreground'
    'status:Show daemon pid, version, uptime'
    'logs:Tail the daemon log'
    'uninstall:Remove the background service'
    'stop:Shut down the supervisor and terminate background sessions'
  )

  _arguments -C \
    '--json-path[Config file (default: ~/.claude/daemon.json)]:path:_files' \
    '--log-file[Log file (default: ~/.claude/daemon.log)]:path:_files' \
    '-h[Display help]' \
    '--help[Display help]' \
    '1: :->command' \
    '*::arg:->args'

  case $state in
    command)
      _describe -t commands 'claude daemon command' daemon_subcommands
      ;;
    args)
      case ${line[1]} in
        run)
          _arguments \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:json-path:_files'
          ;;
        stop)
          _arguments \
            '--any[Also stop a transient (non-service) daemon]' \
            '--keep-workers[Leave detached sessions running]' \
            '-h[Display help]' \
            '--help[Display help]'
          ;;
      esac
      ;;
  esac
}

_claude_auth() {
  local line state

  # shellcheck disable=SC2034
  local -a auth_subcommands=(
    'login:Sign in to your Anthropic account'
    'logout:Log out from your Anthropic account'
    'status:Show authentication status'
  )

  _arguments -C \
    '-h[Display help]' \
    '--help[Display help]' \
    '1: :->command' \
    '*::arg:->args'

  case $state in
    command)
      _describe -t commands 'claude auth command' auth_subcommands
      ;;
    args)
      case ${line[1]} in
        login)
          _arguments \
            '--claudeai[Use Claude subscription (default)]' \
            '--console[Use Anthropic Console]' \
            '--email[Pre-populate email address]:email:' \
            '--sso[Force SSO login flow]' \
            '-h[Display help]' \
            '--help[Display help]'
          ;;
        status)
          _arguments \
            '--json[Output as JSON (default)]' \
            '--text[Output as human-readable text]' \
            '-h[Display help]' \
            '--help[Display help]'
          ;;
      esac
      ;;
  esac
}

_claude_auto_mode() {
  local line state

  # shellcheck disable=SC2034
  local -a auto_mode_subcommands=(
    'config:Print the effective auto mode config as JSON'
    'critique:Get AI feedback on your custom auto mode rules'
    'defaults:Print the default auto mode rules as JSON'
  )

  _arguments -C \
    '-h[Display help]' \
    '--help[Display help]' \
    '1: :->command' \
    '*::arg:->args'

  case $state in
    command)
      _describe -t commands 'claude auto-mode command' auto_mode_subcommands
      ;;
    args)
      case ${line[1]} in
        critique)
          _arguments \
            '--model[Override which model is used]:model:' \
            '-h[Display help]' \
            '--help[Display help]'
          ;;
      esac
      ;;
  esac
}

_claude_mcp() {
  local line state

  # shellcheck disable=SC2034
  local -a mcp_subcommands=(
    'serve:Start the Claude Code MCP server'
    'add:Add an MCP server'
    'remove:Remove an MCP server'
    'list:List configured MCP servers'
    'get:Get details about an MCP server'
    'add-json:Add an MCP server (stdio or SSE) with a JSON string'
    'add-from-claude-desktop:Import MCP servers from Claude Desktop'
    'login:Authenticate with an MCP server'
    'logout:Clear stored OAuth credentials for an MCP server'
    'reset-project-choices:Reset all approved and rejected project-scoped servers'
  )

  _arguments -C \
    '-h[Display help]' \
    '--help[Display help]' \
    '1: :->command' \
    '*::arg:->args'

  case $state in
    command)
      _describe -t commands 'claude mcp command' mcp_subcommands
      ;;
    args)
      case ${line[1]} in
        serve)
          _arguments \
            '-d[Enable debug mode]' \
            '--debug[Enable debug mode]' \
            '--verbose[Override verbose mode setting from config]' \
            '-h[Display help]' \
            '--help[Display help]'
          ;;
        add)
          _arguments \
            '--callback-port[Fixed port for OAuth callback]:port:' \
            '--client-id[OAuth client ID for HTTP/SSE servers]:clientId:' \
            '--client-secret[Prompt for OAuth client secret]' \
            '-e[Set environment variables]:env:' \
            '--env[Set environment variables]:env:' \
            '-H[Set WebSocket headers]:header:' \
            '--header[Set WebSocket headers]:header:' \
            '-s[Configuration scope]:scope:(local user project)' \
            '--scope[Configuration scope]:scope:(local user project)' \
            '-t[Transport type]:transport:(stdio sse http)' \
            '--transport[Transport type]:transport:(stdio sse http)' \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:name:' \
            '2:command or URL:' \
            '*:args:'
          ;;
        remove)
          _arguments \
            '-s[Configuration scope]:scope:(local user project)' \
            '--scope[Configuration scope]:scope:(local user project)' \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:name:'
          ;;
        get)
          _arguments \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:name:'
          ;;
        add-json)
          _arguments \
            '--client-secret[Prompt for OAuth client secret]' \
            '-s[Configuration scope]:scope:(local user project)' \
            '--scope[Configuration scope]:scope:(local user project)' \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:name:' \
            '2:json:'
          ;;
        add-from-claude-desktop)
          _arguments \
            '-s[Configuration scope]:scope:(local user project)' \
            '--scope[Configuration scope]:scope:(local user project)' \
            '-h[Display help]' \
            '--help[Display help]'
          ;;
        login)
          _arguments \
            '--no-browser[Print the authorization URL instead of opening a browser]' \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:name:'
          ;;
        logout)
          _arguments \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:name:'
          ;;
      esac
      ;;
  esac
}

_claude_plugin() {
  local line state

  # shellcheck disable=SC2034
  local -a plugin_subcommands=(
    'details:Show a plugin component inventory and projected token cost'
    'disable:Disable an enabled plugin'
    'enable:Enable a disabled plugin'
    'eval:Run eval cases against a plugin and report scored results'
    'init:Scaffold a new plugin'
    'new:Scaffold a new plugin'
    'install:Install a plugin from available marketplaces'
    'i:Install a plugin from available marketplaces'
    'list:List installed plugins'
    'marketplace:Manage Claude Code marketplaces'
    'prune:Remove auto-installed dependencies that are no longer needed'
    'autoremove:Remove auto-installed dependencies that are no longer needed'
    'tag:Create a git tag for a plugin release'
    'uninstall:Uninstall an installed plugin'
    'remove:Uninstall an installed plugin'
    'update:Update a plugin to the latest version'
    'validate:Validate a plugin or marketplace manifest'
  )

  _arguments -C \
    '-h[Display help]' \
    '--help[Display help]' \
    '1: :->command' \
    '*::arg:->args'

  case $state in
    command)
      _describe -t commands 'claude plugin command' plugin_subcommands
      ;;
    args)
      case ${line[1]} in
        details)
          _arguments \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:name:'
          ;;
        validate)
          _arguments \
            '--strict[Treat warnings as errors (exit 1)]' \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:path:_files'
          ;;
        marketplace)
          _claude_plugin_marketplace
          ;;
        install|i)
          _arguments \
            '--config[Set a userConfig option declared in the plugin manifest]:key=value:' \
            '-s[Installation scope]:scope:(user project local)' \
            '--scope[Installation scope]:scope:(user project local)' \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:plugin:'
          ;;
        uninstall|remove)
          _arguments \
            '--keep-data[Preserve the plugin persistent data directory]' \
            '--prune[Also remove auto-installed dependencies that are no longer needed]' \
            '-s[Uninstall from scope]:scope:(user project local)' \
            '--scope[Uninstall from scope]:scope:(user project local)' \
            '-y[Skip the --prune confirmation prompt]' \
            '--yes[Skip the --prune confirmation prompt]' \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:plugin:'
          ;;
        update)
          _arguments \
            '-s[Installation scope]:scope:(user project local managed)' \
            '--scope[Installation scope]:scope:(user project local managed)' \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:plugin:'
          ;;
        list)
          _arguments \
            '--available[Include available plugins from marketplaces (requires --json)]' \
            '--json[Output as JSON]' \
            '-h[Display help]' \
            '--help[Display help]'
          ;;
        enable)
          _arguments \
            '-s[Installation scope]:scope:(user project local)' \
            '--scope[Installation scope]:scope:(user project local)' \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:plugin:'
          ;;
        disable)
          _arguments \
            '-a[Disable all enabled plugins]' \
            '--all[Disable all enabled plugins]' \
            '-s[Installation scope]:scope:(user project local)' \
            '--scope[Installation scope]:scope:(user project local)' \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:plugin:'
          ;;
        init|new)
          _arguments \
            '--author[Author name]:name:' \
            '--author-email[Author email]:email:' \
            '--description[Manifest description]:text:' \
            '-f[Overwrite an existing .claude-plugin/ at the target]' \
            '--force[Overwrite an existing .claude-plugin/ at the target]' \
            '--with[Also scaffold components]:components:(skills agents hooks mcp lsp output-style channel)' \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:name:'
          ;;
        prune|autoremove)
          _arguments \
            '--dry-run[List what would be removed without removing]' \
            '-s[Prune at scope]:scope:(user project local)' \
            '--scope[Prune at scope]:scope:(user project local)' \
            '-y[Skip the confirmation prompt]' \
            '--yes[Skip the confirmation prompt]' \
            '-h[Display help]' \
            '--help[Display help]'
          ;;
        tag)
          _arguments \
            '--dry-run[Print what would be tagged without creating it]' \
            '-f[Skip the dirty-working-tree and tag-already-exists checks]' \
            '--force[Skip the dirty-working-tree and tag-already-exists checks]' \
            '-m[Tag annotation message]:msg:' \
            '--message[Tag annotation message]:msg:' \
            '--push[Push the tag to --remote after creating it]' \
            '--remote[Remote to push to with --push]:name:' \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:path:_files'
          ;;
        eval)
          _arguments \
            '--ablation[Run a no-plugin baseline arm and report the score delta]:mode:(none with-without)' \
            '--allow-tools[Operator grant for gated tools]:tools:' \
            '--case[Filter cases by name glob]:glob:' \
            '--json[Emit aggregate-result.json to stdout]' \
            '--judge-model[Override LLM-grader model]:model:' \
            '--keep-temp[Preserve scaffold dirs for debugging]' \
            '--max-cost-usd[Optional hard cost ceiling]:usd:' \
            '--model[Override model for all cases]:model:' \
            '--no-scaffold[Explicitly skip scaffold_script]' \
            '--output-dir[Directory for aggregate-result.json]:dir:_directories' \
            '--runs[Override per-case runs]:n:' \
            '--scaffold[Run each case scaffold_script]' \
            '--tag[Filter cases by tag]:tag:' \
            '--threshold[Exit 1 if any case score is below this threshold]:0..1:' \
            '--verbose[Stream the trace as it runs]' \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:target:_files'
          ;;
      esac
      ;;
  esac
}

_claude_plugin_marketplace() {
  local line state

  # shellcheck disable=SC2034
  local -a marketplace_subcommands=(
    'add:Add a marketplace from a URL, path, or GitHub repo'
    'list:List all configured marketplaces'
    'remove:Remove a configured marketplace'
    'rm:Remove a configured marketplace'
    'update:Update marketplace(s) from their source'
  )

  _arguments -C \
    '-h[Display help]' \
    '--help[Display help]' \
    '1: :->command' \
    '*::arg:->args'

  case $state in
    command)
      _describe -t commands 'claude plugin marketplace command' marketplace_subcommands
      ;;
    args)
      case ${line[1]} in
        add)
          _arguments \
            '--scope[Where to declare the marketplace]:scope:(user project local)' \
            '--sparse[Limit checkout to specific directories]:paths:' \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:source:'
          ;;
        remove|rm)
          _arguments \
            '--scope[Remove the marketplace declaration from a specific settings scope]:scope:(user project local)' \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:name:'
          ;;
        update)
          _arguments \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:name:'
          ;;
        list)
          _arguments \
            '--json[Output as JSON]' \
            '-h[Display help]' \
            '--help[Display help]'
          ;;
      esac
      ;;
  esac
}

_claude_project() {
  local line state

  # shellcheck disable=SC2034
  local -a project_subcommands=(
    'purge:Delete all Claude Code state for a project'
  )

  _arguments -C \
    '-h[Display help]' \
    '--help[Display help]' \
    '1: :->command' \
    '*::arg:->args'

  case $state in
    command)
      _describe -t commands 'claude project command' project_subcommands
      ;;
    args)
      case ${line[1]} in
        purge)
          _arguments \
            '-h[Display help]' \
            '--help[Display help]' \
            '1:path:_directories'
          ;;
      esac
      ;;
  esac
}

_claude_install() {
  _arguments \
    '--force[Force installation even if already installed]' \
    '-h[Display help]' \
    '--help[Display help]' \
    '1:target:(stable latest)'
}

compdef _claude claude
