cask_args appdir: '/Applications'

tap 'homebrew/bundle'

# OS X Apps via Homebrew
# https://caskroom.github.io/
tap 'caskroom/cask'

brew 'awscli'
brew 'coreutils'
brew 'dos2unix'
brew 'git'
brew 'go'
brew 'grc'
brew 'httpie'
brew 'hub'
brew 'jq'
brew 'node'
brew 'openssl'
brew 'postgresql'
brew 'rbenv'
brew 'stout'
brew 's3cmd'
brew 'sshuttle'
brew 'the_silver_searcher'
brew 'wget'
brew 'wrk'
brew 'youtube-dl'
brew 'zsh'

cask 'alfred'
cask 'chefdk'
cask 'evernote'
cask 'flux'
cask 'google-chrome'
cask 'rescuetime'
cask 'vlc'
