catppuccin/themes/catppuccin_frappe.theme:$XDG_CONFIG_HOME/btop/themes/catppuccin_frappe.theme
catppuccin/themes/catppuccin_latte.theme:$XDG_CONFIG_HOME/btop/themes/catppuccin_latte.theme
catppuccin/themes/catppuccin_macchiato.theme:$XDG_CONFIG_HOME/btop/themes/catppuccin_macchiato.theme
catppuccin/themes/catppuccin_mocha.theme:$XDG_CONFIG_HOME/btop/themes/catppuccin_mocha.theme
