config:$XDG_CONFIG_HOME/bat/config
catppuccin/themes/Catppuccin Frappe.tmTheme:$XDG_CONFIG_HOME/bat/themes/Catppuccin Frappe.tmTheme
catppuccin/themes/Catppuccin Latte.tmTheme:$XDG_CONFIG_HOME/bat/themes/Catppuccin Latte.tmTheme
catppuccin/themes/Catppuccin Macchiato.tmTheme:$XDG_CONFIG_HOME/bat/themes/Catppuccin Macchiato.tmTheme
catppuccin/themes/Catppuccin Mocha.tmTheme:$XDG_CONFIG_HOME/bat/themes/Catppuccin Mocha.tmTheme
