// herdr's agent-detection manifests: reading one, composing an overlay onto one,
// and cutting a single rule back out of an overlay. bin/herdr-agent-detection is
// the only caller.
//
// TOML is parsed here rather than shelled out to yq, and the reason is the guard
// the yq call existed to serve: a read that yields no working rules has to be
// distinguishable from a read that failed, because both `sync` and `check` act on
// an empty set by reporting that herdr dropped its rules. Bun.TOML.parse draws
// that line where yq cannot. yq exits 0 with empty output for a manifest holding
// no `rules` key at all, so a truncated cache read as a manifest whose rules all
// went away. It also accepts a duplicate top-level key and keeps the last, while
// herdr's own Rust parser rejects the file and silently falls back to its cached
// remote, so the "is this valid TOML" gate passed exactly the file it exists to
// stop. Bun.TOML.parse throws on both, which is what herdr does.
//
// It is still not herdr's parser, so the gate stays a proxy. The `remote:` check
// in the scorer is the real one.

import { readFileSync } from "node:fs";

// Matched as a prefix of the first line only. A file whose first line starts with
// it is this program's to overwrite and to delete, and anything else under the
// install directory belongs to whoever put it there.
export const GENERATED_MARKER = "# Generated by bin/herdr-agent-detection";

const TRAILING_NEWLINES = /\n+$/;

// The line an overlay carries recording the working rules it was written
// against. The value is textual on purpose: a TOML parser has no place for a
// comment and would drop it.
const RECORDED_RULES = /^# base-working-rules: */;

const RULES_HEADER = /^\[\[rules\]\]/;

export type Manifest = Record<string, unknown>;

// Undefined is "could not be read", and callers must keep it apart from a
// manifest that parsed. Folding the two together is how a parse failure reports
// as herdr having dropped every working rule.
export function parseManifest(text: string): Manifest | undefined {
  let parsed: unknown;
  try {
    parsed = Bun.TOML.parse(text);
  } catch {
    return undefined;
  }
  return isRecord(parsed) ? parsed : undefined;
}

export function readManifest(path: string): Manifest | undefined {
  const text = readText(path);
  return text === undefined ? undefined : parseManifest(text);
}

export function versionOf(text: string): string {
  const parsed = parseManifest(text);
  if (parsed === undefined) return "unknown";
  return scalar(parsed.version) || "unknown";
}

export function manifestVersion(path: string): string {
  return versionOf(readText(path) ?? "");
}

// The ids of every rule in a manifest that can score `working`, or undefined when
// the manifest could not be read. A manifest carrying no `rules` key is one of
// those. Every herdr manifest declares rules, so a file holding none is a
// truncated read or another file entirely, and the launchd watcher fires on the
// very write that can produce one.
export function workingRuleIds(text: string): string[] | undefined {
  const parsed = parseManifest(text);
  if (parsed === undefined) return undefined;
  if (!Array.isArray(parsed.rules)) return undefined;

  const ids: string[] = [];
  for (const rule of parsed.rules) {
    if (!isRecord(rule) || rule.state !== "working") continue;
    const id = scalar(rule.id);
    if (id !== "") ids.push(id);
  }
  return sortIds(ids);
}

// One explicit comparator for both sides of the drift comparison. The set is also
// what a person reads out of the drift message and retypes onto the
// `# base-working-rules:` line, so ordering it by code unit rather than by the
// ambient locale's collation keeps a 3am run and a hand run naming the same list.
export function sortIds(ids: string[]): string[] {
  return [...ids].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
}

// The set the overlay recorded when it was written. The first matching line wins,
// and an overlay carrying no such line recorded the empty set.
export function recordedWorkingRuleIds(text: string): string[] {
  for (const line of text.split("\n")) {
    const match = RECORDED_RULES.exec(line);
    if (match === null) continue;
    return sortIds(line.slice(match[0].length).split(/\s+/).filter((word) => word !== ""));
  }
  return [];
}

// The rule ids an overlay declares, in manifest order, which is the order
// ablation takes them out in.
export function ruleIdsOf(text: string): string[] {
  const parsed = parseManifest(text);
  if (parsed === undefined || !Array.isArray(parsed.rules)) return [];
  const ids: string[] = [];
  for (const rule of parsed.rules) {
    if (!isRecord(rule)) continue;
    const id = scalar(rule.id);
    if (id !== "") ids.push(id);
  }
  return ids;
}

// Both halves are read before anything is emitted, and either one empty fails the
// whole compose. Streaming the base straight out would let a base that vanishes
// mid-run produce an overlay-only manifest: valid TOML, installs cleanly, and
// silently drops every upstream rule including the blocked-prompt ones. Composing
// exists to keep those, so anything less than both halves is not a manifest to
// install.
export function composeText(
  agent: string,
  baseText: string,
  overlayText: string,
): string | undefined {
  const base = baseText.replace(TRAILING_NEWLINES, "");
  const overlay = overlayText.replace(TRAILING_NEWLINES, "");
  if (base === "" || overlay === "") return undefined;

  return [
    `${GENERATED_MARKER}: herdr's cached ${agent} manifest`,
    `# ${versionOf(base)}, with herdr/agent-detection/${agent}.toml appended. A local`,
    "# override replaces the remote manifest rather than merging with it, so the whole",
    "# manifest has to be here. Edit the overlay in the dotfiles repo. Edits to this",
    "# file are overwritten by the next `herdr-agent-detection sync`.",
    "",
    base,
    "",
    overlay,
  ].join("\n");
}

export function compose(agent: string, basePath: string, overlayPath: string): string | undefined {
  const base = readText(basePath);
  const overlay = readText(overlayPath);
  if (base === undefined || overlay === undefined) return undefined;
  return composeText(agent, base, overlay);
}

// The composed text carries no trailing newline, and the file on disk ends with
// exactly one. Every comparison against an installed file normalises both sides
// the same way.
export function stripTrailingNewlines(text: string): string {
  return text.replace(TRAILING_NEWLINES, "");
}

export function isGenerated(path: string): boolean {
  const text = readText(path);
  if (text === undefined) return false;
  return text.split("\n")[0].startsWith(GENERATED_MARKER);
}

// The overlay with one rule taken out, cut from the text rather than
// round-tripped through the parser. The parser has no place for a comment and
// emits none, and this file is mostly comments explaining what each rule is for.
// Losing them changes nothing about how the remaining rules score, and it makes
// an ablated overlay unreadable when a run wants looking at.
//
// A comment block sitting between two rules is attributed to the preceding one,
// so dropping rule N also drops the leading comments of rule N+1. Cosmetic: it
// does not reach the scoring.
export function overlayWithout(text: string, target: string): string {
  const lines = text.split("\n");
  // The trailing newline leaves a final empty element that was never a line.
  if (lines.length > 0 && lines[lines.length - 1] === "") lines.pop();

  let kept = "";
  let block: string[] | undefined;
  let drop = false;

  for (const line of lines) {
    if (RULES_HEADER.test(line)) {
      if (block !== undefined && !drop) kept += block.join("");
      block = [`${line}\n`];
      drop = false;
      continue;
    }
    if (block === undefined) {
      kept += `${line}\n`;
      continue;
    }
    if (line === `id = "${target}"`) drop = true;
    block.push(`${line}\n`);
  }
  if (block !== undefined && !drop) kept += block.join("");

  return kept;
}

function readText(path: string): string | undefined {
  try {
    return readFileSync(path, "utf8");
  } catch {
    return undefined;
  }
}

// A version or an id spelled as a TOML integer is still the value the manifest
// names. Anything with no single spelling is nothing a caller can use.
function scalar(value: unknown): string {
  if (typeof value === "string") return value;
  if (typeof value === "number" || typeof value === "bigint" || value === true) return String(value);
  return "";
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
