#!/usr/bin/env bash
# shellcheck disable=SC2059
#
# bootstrap installs things.

cd "$(dirname "$0")/.." || exit 1
DOTFILES_ROOT=$(pwd -P)

# Parse arguments
NO_PROMPT=false
for arg in "$@"; do
  case $arg in
    --no-prompt) NO_PROMPT=true ;;
  esac
done

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit 1
}

setup_gitconfig () {
  if ! [ -f git/config.local ]
  then
    # Skip gitconfig setup in no-prompt mode
    if [ "$NO_PROMPT" == "true" ]; then
      info 'skipping gitconfig setup (no-prompt mode)'
      return
    fi

    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your github author name?'
    read -r -e git_authorname
    user ' - What is your github author email?'
    read -r -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/config.local.example > git/config.local

    success 'gitconfig'
  fi
}

install_dotfiles () {
  info 'installing dotfiles'
  mkdir -p "$HOME/.ssh"
  ln -sf "$DOTFILES_ROOT/ssh/config" "$HOME/.ssh/config"
  success "linked ssh/config"
}

setup_gitconfig
install_dotfiles

info 'building default packages'
./bin/build-default-packages

# shellcheck disable=SC1091
if source ./bin/dotf
then
  success "dependencies installed"
else
  fail "error installing dependencies"
fi

echo ''
echo '  All installed!'
