#!/usr/bin/env zsh
#
# Run all dotfiles installers.

set -e

cd "$(dirname "$0")"/..

echo "› brew bundle"
brew bundle

# Expose brew configuration to installers
eval "$(brew shellenv)"

# Activate mise shims so that installers can use any shell
eval "$(mise activate --shims)"

# TEMP: run go first since it has an mise-dependent installer
./go/install.sh

# find the installers and run them iteratively
find . -name install.sh ! -path "./mise/*" | while read -r installer ; do "${installer}"; done
