[plugin]
deps = []

[[flavor.deps]]
use = "yazi-rs/flavors:catppuccin-mocha"
rev = "0f9204b"
hash = "7dfe41c9c3d9be76da8a844263d0bbed"

[[flavor.deps]]
use = "yazi-rs/flavors:catppuccin-latte"
rev = "0f9204b"
hash = "b8f46853c27707115f25f3423a47bd38"
