source-file ~/.config/tmux/options.conf
source-file ~/.config/tmux/keys.conf
source-file ~/.config/tmux/plugins.conf
source-file -q ~/.config/tmux/tmux.conf.local
run '~/.config/tmux/plugins/tpm/tpm'
source-file ~/.config/tmux/status.conf
