#!/usr/bin/env bash
# shellcheck disable=SC2329,SC2016

Describe "herdr-agent-detection"
  script="$SHELLSPEC_PROJECT_ROOT/../bin/herdr-agent-detection"

  setup() {
    root=$(mktemp -d)
    export XDG_STATE_HOME="$root/state"
    export XDG_CONFIG_HOME="$root/config"
    base="$XDG_STATE_HOME/herdr/agent-detection/remote/claude.toml"
    override_dir="$XDG_CONFIG_HOME/herdr/agent-detection"
    installed="$override_dir/claude.toml"
    mkdir -p "${base%/*}" "$override_dir" "$root/stub" "$root/empty"

    # `sync` reloads herdr after it writes, and gives up on a machine with no
    # herdr at all. Neither belongs in a test of what it writes.
    printf '#!/bin/sh\nexit 0\n' >"$root/stub/herdr"
    chmod +x "$root/stub/herdr"
  }

  cleanup() {
    rm -rf "$root"
  }

  BeforeEach 'setup'
  AfterEach 'cleanup'

  # The script is zsh, so ~/.zshenv runs and brew shellenv in it can put the
  # real herdr back ahead of the stub. An empty ZDOTDIR leaves $PATH alone.
  run_script() {
    PATH="$root/stub:$PATH" ZDOTDIR="$root/empty" "$script" "$@"
  }

  # Stands in for herdr's own manifest, carrying the working rules the shipped
  # overlay records and the idle rule it outranks.
  write_base() {
    cat >"$base" <<'TOML'
id = "claude"
version = "2026.01.01.1"
min_engine_version = 2

[[rules]]
id = "osc_title_working"
state = "working"
priority = 1100
region = "osc_title"

[[rules]]
id = "btw_overlay_working"
state = "working"
priority = 975
region = "bottom_non_empty_lines(5)"

[[rules]]
id = "live_prompt_box"
state = "idle"
priority = 950
region = "prompt_box_body"
TOML
  }

  It "installs the cached manifest with the overlay appended"
    composed() {
      write_base
      run_script sync >/dev/null || return
      cat "$installed"
    }
    When call composed
    The status should be success
    The output should include 'id = "live_prompt_box"'
    The output should include 'id = "local_spinner_line_working"'
  End

  It "installs nothing when herdr has cached no manifest"
    without_base() {
      run_script sync 2>/dev/null || return
      test ! -e "$installed"
    }
    When call without_base
    The status should be success
  End

  It "reports an install left behind by a newer manifest"
    stale() {
      write_base
      run_script sync >/dev/null
      sed 's/2026.01.01.1/2026.02.02.1/' "$base" >"$base.new" && mv "$base.new" "$base"
      run_script check
    }
    When call stale
    The status should be failure
    The output should include "is behind manifest 2026.02.02.1"
  End

  It "reports a manifest that changed which of its rules score working"
    drifted() {
      write_base
      run_script sync >/dev/null
      cat >>"$base" <<'TOML'

[[rules]]
id = "screen_spinner_working"
state = "working"
priority = 960
region = "bottom_non_empty_lines(10)"
TOML
      run_script check
    }
    When call drifted
    The status should be failure
    The output should include "scores working from"
    The output should include "screen_spinner_working"
  End

  It "takes back a file it generated once its overlay is gone"
    orphan() {
      write_base
      printf '%s\n' "# Generated by bin/herdr-agent-detection: codex" \
        >"$override_dir/codex.toml"
      run_script sync >/dev/null || return
      test ! -e "$override_dir/codex.toml"
    }
    When call orphan
    The status should be success
  End

  It "leaves an override it did not generate alone"
    hand_written() {
      write_base
      printf '%s\n' 'id = "codex"' >"$override_dir/codex.toml"
      run_script sync >/dev/null || return
      test -e "$override_dir/codex.toml"
    }
    When call hand_written
    The status should be success
  End
End
