name: shellcheck
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ludeeus/action-shellcheck@1.0.0
        env:
          SHELLCHECK_OPTS: -e SC1071
